import Head from 'next/head'

import Banner from '../components/banner/banner'
import Card from '../components/card/card' ;
 
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { fetchCoffeeStores } from '../lib/coffee-store';


export async function getStaticProps(){
  console.log('inside getStaticProps function ')

  const coffeeStores = await fetchCoffeeStores() ; 

  
  return {
    props :{
      coffeeStores: coffeeStores, 
    }, 
  }
  
}


export default function Home(props) {
  console.log(props);
  const changeButton = () => {
    console.log('Button clicked');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby " handleOnClick={changeButton}/>
         <div className={styles.heroImage}>
        <Image src="/static/hero-image.png" width={700} height={400}/>
        </div>

        {props.coffeeStores.length >0 && (
        <>
        <h2 className={styles.heading2}>Toronto Stores</h2>

        <div className={styles.cardLayout}>
          {
            props.coffeeStores.map( (coffeestore)=>{
               return(<Card 
                key={coffeestore.id}
               name={coffeestore.name}
                href = {`/coffee-store/${coffeestore.id}`}
                 imgUrl={coffeestore.imgUrl || "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"} 
               className={styles.card}
             />) ;
              })}
        </div>  
          </> )}

      </main>
    </div>
  )
}
